language: cpp
matrix:
  include:
  - os: osx
    compiler: clang
    arch: amd64
    env: GROK_CI_BUILD_CONFIGURATION=Release GROK_CI_INCLUDE_IF_DEPLOY=1 GROK_NONCOMMERCIAL=1
    addons:
      homebrew:
        packages:
          - p7zip
          - cmake
        update: true
  - os: linux
    arch: amd64
    dist: bionic 
    sudo: required
    compiler: g++-9
    env: 
      - GROK_CI_BUILD_CONFIGURATION=Release GROK_CI_INCLUDE_IF_DEPLOY=1 GROK_NONCOMMERCIAL=1
      - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-9
before_install:
    - eval "${MATRIX_EVAL}"
install:
- "./tools/travis-ci/install.sh"
script:
- "./tools/travis-ci/run.sh"
before_deploy:
- export GROK_RELEASE_PKG_FILE=$(ls build/grok-${TRAVIS_TAG}*)
- echo "deploying $GROK_RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: a3mnuIXX+kfYJRBWDG8zd2oMP312PBk2K+DuzxPRiXCA99fYcTbpfqPnMSRxomtl0+p/lv8aQury5doI+E9FkjQu1Ct7q+rQM81vBRnrmc3nJFgzaAYWBwyavdKpVSD4YpyFV3mPLCzILk74r7UKEE5yJDxi2Q8IuchN6WHo5A9seHZ52gORqonhEHZipRsN2HhINP824HxLuEd+43fQN5XRJ2Oe+GxPdl6a2dohE7iPkNAc5xeX/RZ+DI+OV7XdFAg1922W2TuVYXKcGWZZRoGU/JmRbkEGrDSdcmOjvaRLRYfYvyD57cIw4l+41VQIxr7i+Zjc4cF1+4gwHSwXY8TBOXILXZ8z28NudxOlr2I0WeEuVrHZQ/ufzDVAmReB7LSN4QU5GhUm+tYMeWrU9PFyi+SJIv2N6/yTAMC4FHcVl3hoGrFgyJb4ySH2axLi+kRHynG3z2W1jC9XCJxVs2h+cxRdEfb+yLfJ83R0Hsmeg0+eUcn0f5ULVJjf2QePEH9TSC26+mnZGg2HsOCEw8qPDqAJRUZQRHzVNIBGR0hQl7snALQCFmEF+SRwT5Nq5rDXZc0rB/8ikIyn3I8ctmVjS23IHpyVpipMw18aLpiGOaYAFaV+hLhgVHhkxsIVvxogjGo6AZblgjBjSQw2qiIXSFjJs7VyrmtEJVsV598=
  file_glob: true
  file: "${GROK_RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    repo: GrokImageCompression/grok
    tags: true
    condition: "$GROK_CI_INCLUDE_IF_DEPLOY = 1"

