version: 3.0.0.{build}
clone_depth: 50
environment:
  VCVAR2019: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat'
  matrix:
  - GROK_CI_ARCH: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GROK_CI_VCVARS: $(VCVAR2019)
    GROK_NONCOMMERCIAL: 1
    GROK_CI_INCLUDE_IF_DEPLOY: 1    
  - GROK_CI_ARCH: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GROK_CI_VCVARS: $(VS140COMNTOOLS)..\..\VC\vcvarsall.bat
    GROK_NONCOMMERCIAL: 1
    GROK_CI_INCLUDE_IF_DEPLOY: 1    
  - GROK_CI_ARCH: x64  
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GROK_CI_VCVARS: $(VS140COMNTOOLS)..\..\VC\vcvarsall.bat
    GROK_NONCOMMERCIAL: 1
    GROK_CI_INCLUDE_IF_DEPLOY: 1
  - GROK_CI_ARCH: x64  
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GROK_CI_VCVARS: $(VCVAR2019)
    GROK_NONCOMMERCIAL: 1
    GROK_CI_INCLUDE_IF_DEPLOY: 1    
install:
- cmd: c:\cygwin\bin\bash ./tools/travis-ci/install.sh
build_script:
- cmd: >-
    "%GROK_CI_VCVARS%" %GROK_CI_ARCH%

    bash ./tools/travis-ci/run.sh
test: off
deploy:
  #release: grok-$(appveyor_repo_tag_name)
  description: 'Grok $(appveyor_repo_tag_name) has been released.'
  provider: GitHub
  auth_token:
    secure: wBy109xKkI+vEJvY+IFO3ULME+NZJKqhxqZMUpTMJRHWhO1DsntmXefWV2t45wyF
  artifact: /.*\.zip/            # upload all zip packages to release assets
  draft: false
  prerelease: false
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    appveyor_repo_tag: true        # deploy on tag push only
    GROK_CI_INCLUDE_IF_DEPLOY: 1
